### ISSUE TITLE
Closure[ARKNIGHTS][""]++ 遇到错误: Invalid time value

### ISSUE THREAD

**Issue by HydrogenDeuterium** [orz-tools/cpp#13]
```
Invalid time value
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36 Edg/129.0.0.0
RangeError: Invalid time value
    at mM (https://cpp.orz.tools/assets/vendor-99b30a9c.js:53:23626)
    at https://cpp.orz.tools/assets/index-a2580c91.js:2:29284
    at Jh (https://cpp.orz.tools/assets/vendor-99b30a9c.js:42:19518)
    at lp (https://cpp.orz.tools/assets/vendor-99b30a9c.js:44:3139)
    at bw (https://cpp.orz.tools/assets/vendor-99b30a9c.js:44:2351)
    at P0 (https://cpp.orz.tools/assets/vendor-99b30a9c.js:44:1893)
    at Ww (https://cpp.orz.tools/assets/vendor-99b30a9c.js:44:47315)
    at Uw (https://cpp.orz.tools/assets/vendor-99b30a9c.js:44:39763)
    at i5 (https://cpp.orz.tools/assets/vendor-99b30a9c.js:44:39691)
    at Cu (https://cpp.orz.tools/assets/vendor-99b30a9c.js:44:39545)
```
# 页面截图

![image](https://github.com/user-attachments/assets/5abc372d-0856-41a9-938a-fbad4ba6abd5)

# 触发条件

点击下图红框链接

![image](https://github.com/user-attachments/assets/c944cb24-7293-4931-86b2-ef6a20682fd8)

# 尝试过的解决方案

- 清除浏览器缓存数据
- 更新本地系统时间
- 更换浏览器（Edge->Firefox）

以上解决方法均无法起效

**Comment by HydrogenDeuterium** [comment]
更新：
1. 使用移动版浏览器（Edge 移动版）访问，出现相同报错
2. 访问 1999，不出现此类报错

**Comment by oott123** [comment]
确认是数据脚本跑飞，已修正数据源，等下午4点半左右例行更新恢复

**Comment by oott123** [comment]
已修正。
